<footer>
    <img alt="Licencia de Creative Commons" style="border-width:0"
        src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/"
        property="dct:title">TiendaOnline</span> by <span xmlns:cc="http://creativecommons.org/ns#"
        property="cc:attributionName">Diego Brito</span> is licensed under a Creative Commons Reconocimiento 4.0.
    Internacional License</a>.
</footer>
</body>
<!-- <?php $conn = null;?> -->

</html>