<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tienda Online</title>
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:200,400&display=swap" rel="stylesheet">
    <style>
        a {
            text-decoration: none;
            color: white;
        }
        a:hover {
            color: white;
        }
    </style>
</head>

<body>
    <header>
        <div class="container-sm sticky-top justify-content-sm-center text-center">
            <h1>Tienda Online</h1>
            <h3>Lámparas Taburiente</h3>
        </div>

    </header>